### ISSUE TITLE
JSON not updated

### ISSUE THREAD

**Issue by FVMF** [khaaarl/tts-asset-reuploader#1]
I ran the script and although it found 267 things that were 404-ing but cached, it did not update any URL's in either the backup file or the original file. So uploading the missing files does nothing in TTS.

**Comment by khaaarl** [comment]
Hmm, interesting. Can we talk more on Discord to get into details? ("khaaarl" on discord, probably findable via the 40k tts discord)

**Comment by FVMF** [comment]
@khaaarl I sent you a friend request on Discord

**Comment by khaaarl** [comment]
Fixed the problem (older cloud links) after discussion on discord!
